### ISSUE TITLE
Doesn't lint

### ISSUE THREAD

**Issue by AgentME** [AtomLinter/linter-jsxhint#10]
I have linter, linter-jshint, linter-jsxhint, and language-jsx installed. I have the following jsx file which should produce a warning for a missing semicolon and eval usage:

```
/** @jsx React.DOM */

var a = <div>Foo {test}</div>;

var b = <div>Foo {" "} {test}</div>;

var x = 9
var y = 100;
z = eval('aaa');
```

If I run jsxhint against the file, it shows me the 2 errors. However, atom doesn't highlight those lines and it doesn't seem like linter-jsxhint is having any effect. linter-jshint works fine on js files.

**Comment by dmnd** [comment]
Confusingly, language-jsx is not React's JSX. It's some other kind of
Javascript language thing. Try installing this instead:
https://atom.io/packages/react

**Comment by AgentME** [comment]
Oh thanks, that did the trick! Maybe a note should be added to the readme mentioning the react package as a requirement?

**Comment by ehd** [comment]
@dmnd I have latest versions of linter, linter-jshint, linter-jsxhint and react installed, but I'm not getting any linter action when the "JavaScript (JSX)" grammar (source.js.jsx) is enabled. It works well for plain JavaScript though. Any ideas why the linter won't jump in? FYI, I've also got file-types installed which is setting the source.js.jsx grammar for all JS files.

**Comment by dmnd** [comment]
Not sure @ehd. I'd debug by trying a JSX file and turing on Linter Debug in Liter settings. 

Also, FYI, jsxhint is being sunset as eslint has added more robust support for JSX, so maybe just switch to that.

**Comment by iam4x** [comment]
I added a reference on `README.md` just comment if should not be closed.

**Comment by aradeonas** [comment]
I have the same problem as @ehd .  Just installed a fresh 0.206  Atom,React,linter, linter-jshint and linter-jsxhint and it works well for JS but doesnt for JSX file.
Any idea?

**Comment by ehd** [comment]
I switched to eslint because I like their features and progress more:
linter, linter-eslint

**Comment by aradeonas** [comment]
So how you configure it for jsx?

**Comment by ehd** [comment]
Use babel-eslint as the eslint parser, it should just work. It's made for
everything babel supports which includes jsx. Also: install all of that as
local dev dependencies

**Comment by aradeonas** [comment]
I cant make eslint work for jsx.So linter-jsxhint doesn't work ?
