### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by imalitavakoli** [AtomLinter/linter-jsxhint#25]
For me it seems the linter is not working!
Although I have installed [React](https://atom.io/packages/react) But it's not yet working.
It recognizes the language right "Javascript(JSX)" but when it sees an opening tag, it says "Unclosed regular expression"! As it's a regular Javascript code... I have already installed "Linter-jshint"

Any ideas?

**Comment by callmewhy** [comment]
same problem...

**Comment by kepler0** [comment]
It seems that this package has been deprecated and no one has forked the package to update it.

If someone were to submit an updated pull request, I'm sure @steelbrain would love to accept and let that person become maintainer of the package.

**Comment by kepler0** [comment]
As well have you guys looked at #17? There is some discussion about JSXHint being discontinued...

**Comment by Arcanemagus** [comment]
Marking as a duplicate of #21.
